sudo: true
language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
#  - "nightly" # currently points to 3.7-dev

before_install:
  - sudo apt install python-logilab-common
  - sudo pip install pytest pytest-cov

# command to install dependencies
install: 
  - pip install -e .

# command to run tests
script: 
  - pytest --cov

# after_success:
#   - codecov
