sudo: true
language: python
python:
  - "2.7"
  # - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
#  - "nightly" # currently points to 3.7-dev

before_install:
  - pip install pytest pytest-cov

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

# command to install dependencies
install: 
  - pip install -e .

# command to run tests
script: 
  - pytest --cov=badger --cov-branch --cov-report=xml:coverage.xml

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT