# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    working_directory: ~/repo
    
    docker:
      - image: kennethreitz/pipenv:latest

    

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          key: dependencies-{{ checksum "Pipfile.lock" }}

      - run:
          name: install dependencies
          command: |
            pipenv install --dev --ignore-pipfile --verbose

      - save_cache:
          key: dependencies-{{ checksum "Pipfile.lock" }}
          paths:
            - ~/.local/share/virtualenvs
        
        
      # run tests!
      - run:
          name: run tests
          command: |
            pipenv run py.test --junit-xml /tmp/test-results/junit.xml --cov=badger --cov-report=xml:coverage.xml --cov-report=html:/tmp/test-results/coverage --cov-branch

      - store_test_results:
          path: /tmp/test-results

      - store_artifacts:
          path: /tmp/test-results
          destination: test-reports


      # Test running the actual package :)
      - run:
          name: install the package
          command: |
            python setup.py install

      - run:
          name: create build badge
          command: |
            mkdir /tmp/badges
            badger build failed -o /tmp/badges/build.svg -c \#e05d44
          when: on_fail

      - run:
          name: create build success badge
          command: |
            mkdir /tmp/badges
            badger build success -o /tmp/badges/build.svg
          when: on_success

      - run:
          name: create test coverage badge
          command: |
            python .circleci/coverage.py coverage.xml /tmp/badges/coverage.svg
          when: always

      - store_artifacts:
          path: /tmp/badges
          destination: badges

